version: "3.1"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

volumes:
  dbdata6:
